### ISSUE TITLE
Module crashes if field larger than just below 4 kB contains \n sequence

### ISSUE THREAD

**Issue by kolmogorov42** [benkasminbullock/JSON-Parse#35] opened 2016-08-18 16:09 UTC
I'm using 64-bit Strawberry Perl on 64-bit Windows 10.

```
perl -v

This is perl 5, version 20, subversion 1 (v5.20.1) built for MSWin32-x64-multi-thread
```

Here's the minimal script on which I can reproduce the issue:

```perl
#!/usr/bin/perl

use warnings;
use strict;
use v5.14;

use JSON::Parse qw(parse_json);

while (<>) {
    my $entry = parse_json($_);
}
```

Very straightforward.
I'm attaching the TXT file I tried to process. Also very simple: two fields, with "text" just under 4 kB in length and a newline sequence in the middle. Everything is plain ASCII.
[jsonexample.txt](https://github.com/benkasminbullock/JSON-Parse/files/425366/jsonexample.txt)

**Comment by benkasminbullock** [comment] 2016-08-18 22:22
Thank you for taking the time to file this bug report.

The JSON::Parse module doesn't offer incremental parsing, so your code

while (<>) {
my $entry = parse_json($_);
}`

doesn't make sense for this module. You need to give the module a complete
JSON structure.

https://metacpan.org/pod/distribution/JSON-Parse/lib/JSON/Parse.pod#RESTRICTIONS

You don't mention what error you are getting - is it a "segmentation fault"
or similar error, or just the error one would expect when trying to parse
ill-formed input?

I wasn't able to reproduce the error on FreeBSD, but the file you linked to
in your message doesn't have a newline within the JSON anyway. If I added a
newline I just got the completely expected error because the input is
malformed:


[ben@mikan] {07:11 11} Json3 512 $ perl -I blib/lib -I blib/arch
t/kolmorogov42-1.t < jsonexample.txt
JSON error at line 2: Unexpected end of input parsing object starting from
byte 1 at t/kolmorogov42-1.t line 24, <> line 1.

If you're getting a memory error or something it might be a bug in this
module, but if your code just throws the above error that is the design
behaviour.

Thanks again for your input and please let me know if I have misinterpreted
something here.

Best wishes,

Ben Bullock

**Comment by kolmogorov42** [comment] 2016-08-18 22:36
Hi, thanks for the prompt reply.

About the incremental parsing -- I don't think that's what I'm doing. I'm parsing a single line, $_, which consists of a well-formed JSON string.

The kind of error I'm experiencing is a segmentation fault-like error, sorry for having left that out. It's not something "to be expected" like the one you managed to get. The program just crashes.

Also, the newline it's there: the '\n' sequence starts at character 2191 in the file. It is, of course, a literal '\' followed by a literal 'n'. Can you see it?

**Comment by benkasminbullock** [comment] 2016-08-19 00:09
Thanks for your message.

There was a memory corruption issue which was due to this line:

https://github.com/benkasminbullock/JSON-Parse/commit/f0a170c2b6d79f5ea322878845bd5bb508f81484#diff-5896cd6d014d0bb6deff57f66ba3f67eL323

It increments the point to write the string by cur twice and thus it was
writing into the wrong place in memory. This would have affected any user
using long strings with escapes like \n in them, so your bug report may
have saved a lot of future problems for users.

Fixing this line cleared up the problem for me on Strawberry Perl latest
version on Windows 10.

If you have time could you try downloading from CPAN and re-testing with
this version:

https://metacpan.org/release/BKB/JSON-Parse-0.41_01

If you find any problems or any other issues with the module, please let me
know.

If I don't hear back from you I'll close this issue in a week or so.

Thanks again,

Best wishes,

Ben Bullock

**Comment by kolmogorov42** [comment] 2016-08-19 02:00
Very good, I'll try that, but how do I install the new version?

**Comment by benkasminbullock** [comment] 2016-08-19 04:12
Download the file from

https://cpan.metacpan.org/authors/id/B/BK/BKB/JSON-Parse-0.41_01.tar.gz

then install it using cpanm in that directory using the file name:

cpanm JSON-Parse-0.41_01.tar.gz

Maybe there is an option to download from CPAN in cpanm but I don't
remember it.

**Comment by kolmogorov42** [comment] 2016-08-19 10:03
Yes, that would be
```
cpanm BKB/JSON-Parse-0.41_01.tar.gz
```

I didn't know much about cpanm, glad I've learned something here.

**Comment by benkasminbullock** [comment] 2016-08-19 10:53
Is it working now?

**Closed** 2016-08-19 10:55 UTC
