### ISSUE TITLE
discrepancies/issues with warn_only()

### ISSUE THREAD

**Issue by stevieb9** [benkasminbullock/JSON-Parse#34] opened 2016-06-12 15:06 UTC
- docs are very unclear. No usage examples, no explanation of what other functions/methods it should affect
- there are no tests to base any real examples on, or to verify whether the method even works
- calling like `$obj->warn_only(1);` works, but it doesn't affect the `parse_json()` function
- `parse_json()` can't be called as a method, as it doesn't allow the object as the first param, therefore it doesn't appear to do anything (failed loading still raises an exception)

Please see this [PerlMonks thread](http://perlmonks.org/?node_id=1165399) for full details.

**Comment by benkasminbullock** [comment] 2016-06-13 00:31
From looking at the source code, "warn_only" was never implemented, only the "parse_json_safer" works.

**Comment by benkasminbullock** [comment] 2016-06-13 00:53
I've provisionally implemented this method in version 0.40_01. Please download from CPAN and check.

**Comment by benkasminbullock** [comment] 2016-06-13 00:54
> parse_json() can't be called as a method, as it doesn't allow the object as the first param, therefore it doesn't appear to do anything (failed loading still raises an exception)

This is by design. `parse_json` is not a method it is a function. Please use `run` to run the object.

**Comment by benkasminbullock** [comment] 2016-06-13 00:56
> calling like $obj->warn_only(1); works, but it doesn't affect the parse_json() function

It's not meant to affect the parse_json function, the whole reason to have the object is so that the defaults can be altered. Is that really not documented anywhere? I will check the documentation carefully again, but this is a red herring as far as I can imagine.

**Comment by benkasminbullock** [comment] 2016-06-14 00:19
These problems should be fixed by these commits:

commit d22242b3d18d040885f00f831062944595b0b778
Author: Ben Bullock <benkasminbullock@gmail.com>
Date:   Tue Jun 14 09:14:19 2016 +0900

    Pod links

commit cfe45362f502c8ca958852932d5e33a7f95761d6
Author: Ben Bullock <benkasminbullock@gmail.com>
Date:   Tue Jun 14 09:10:45 2016 +0900

    Version to 0.41 and some more documentation.

commit 5c11b43a95522d95e6ae44035ffc9c623a4d9783
Author: Ben Bullock <benkasminbullock@gmail.com>
Date:   Mon Jun 13 09:52:24 2016 +0900

    Implement warn_only method.

**Closed by benkasminbullock** 2016-06-14 00:19 UTC
